---
- name: Fail if keepalived_vip is not defined
  ansible.builtin.fail:
    msg: "The variable 'keepalived_vip' is not defined"
  when: keepalived_vip is not defined

- name: Generate keepalived_password
  ansible.builtin.set_fact:
    keepalived_password: "{{ lookup('password', '/dev/null',  length=12) }}"
  when: keepalived_password is not defined

- name: Display ansible_interfaces for debugging
  debug:
    var: ansible_interfaces

- name: Display non_loopback_interfaces for debugging
  debug:
    var: non_loopback_interfaces

- name: Display extracted interfaces for debugging
  debug:
    var: ansible_interfaces | map('extract', ansible_facts) | list

- name: Find primary network interface
  set_fact:
    primary_interface: "{{ non_loopback_interfaces.0.device }}"
  vars:
    non_loopback_interfaces: "{{ ansible_interfaces | map('extract', ansible_facts) | selectattr('ipv4', 'defined') | selectattr('type', 'ne', 'loopback') | list }}"
- debug: var=primary_interface

- name: Default keepalived_iface to primary_interface if not provided
  ansible.builtin.set_fact:
    keepalived_iface: "{{ primary_interface }}"
  when: keepalived_iface is not defined

- block:
  - name: Install keepalived
    ansible.builtin.package:
      name: keepalived
      state: latest

  - name: Load keepalived.conf
    ansible.builtin.template:
      src: keepalived.conf.j2
      dest: /etc/keepalived
      owner: root
      group: root
      mode: 0644
    notify: restart keepalived

  - name: Enable and start keepalived
    ansible.builtin.systemd: 
      name: keepalived
      state: started
      enabled: true

  - name: Update /etc/hosts
    ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ keepalived_vip }} {{ keepalived_hostname }} {{ keepalived_domain }}"
    line: "{{ keepalived_vip }} {{ keepalived_hostname }} {{ keepalived_domain }}"
    state: present
    when: 
    - keepalived_hostname is defined 
    - keepalived_domain is defined
  become: true
