---
- name: Converge
  hosts: all

  vars: 
    keepalived_vip: 172.17.0.48 # must be same in verify.yaml
    keepalived_action: install
    keepalived_password: makinthingsidempotent
    keepalived_hostname: cluster
    keepalived_domain: local
    debug: true

  roles:
  - RnodeC.keepalived
