---
- name: Converge
  hosts: all

  vars: 
    keepalived_floating_ip: 172.17.0.48 # must be same in verify.yaml
    keepalived_enabled: true
    keepalived_password: makinthingsidempotent

  roles:
  - RnodeC.keepalived
