---
- name: Verify
  hosts: all

  vars:
    keepalived_vip: 172.17.0.48 # must be same in converge.yaml

  tasks:
  - name: Ping keepalived_vip
    ansible.builtin.command: "ping -c 4 {{ keepalived_vip }}"
    register: ping_result
    delegate_to: localhost
    changed_when: false
    failed_when: "'100% packet loss' in ping_result.stdout or '0 received' in ping_result.stdout"

  - name: Show ping results
    ansible.builtin.debug:
      var: ping_result.stdout_lines
